# Change these first
owner: datavoid-team # Your GitHub organization or username, where this repository lives
repo: monitor # The name of this repository

sites:
  - name: Home
    url: https://www.datavoid.in
  - name: Blog
    url: https://blog.datavoid.in
  - name: Hosting Service
    url: https://server.datavoid.in
  - name: Downloader
    url: https://download.datavoid.in
  - name: HelpDesk
    url: https://help.datavoid.in
  - name: Scam Checker
    url: https://scamcheck.datavoid.in
  - name: Affiliate Login
    url: https://affiliate.datavoid.in
  - name: DataVoid Events
    url: https://events.datavoid.in
  - name: DataVoid Search
    url: https://search.datavoid.in
  - name: DataVoid Editor
    url: https://editor.datavoid.in
  - name: DataVoid Surveys
    url: https://survey.datavoid.in
  - name: DataVoid Forms
    url: https://forms.datavoid.in
  - name: DataVoid Creator
    url: https://create.datavoid.in
  - name: Chat
    url: https://chat.datavoid.in
  - name: URL Analyzer
    url: https://analyzer.datavoid.in
  - name: DataVoid ER Wizard
    url: https://erwizard.datavoid.in
  - name: Motion
    url: https://motion.datavoid.in
  - name: DataVoid Console
    url: https://console.datavoid.in
  - name: Typer Dash
    url: https://type.datavoid.in

status-website:
  title: Network Status
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.datavoid.in
  #baseUrl: /monitor
  logoUrl: https://forms.datavoid.in/datavoid.png
  name: Network 
  introTitle: ""
  introMessage: This is a status page which uses **real-time** data from our servers to provide you with **live** updates
  navbar:
    - title: Status
      href: /
    #- title: Github
     # href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: This page is [open source]($REPO), maintained by [DataVoid Community](https://www.datavoid.in)
notifications:
  - type: telegram
  
